controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ackermann_steering_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    door_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rear_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    joints:
      - front_right_steer_joint
      - front_left_steer_joint
    interface_name: position
    command_joints:
      - front_right_steer_joint
      - front_left_steer_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

door_position_controller:
  ros__parameters:
    joints:
      - door_joint
    interface_name: position
    command_joints:
      - door_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

rear_wheel_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    interface_name: velocity
    command_joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
