controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController
    
    door_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
forward_position_controller:
  ros__parameters:
    joints:
      - front_right_steer_joint
      - front_left_steer_joint

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - rear_right_wheel_joint
      - rear_left_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      
door_position_controller:
  ros__parameters:
    joints:
      - door_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity