<?xml version="1.0"?>

<robot name="deliverybot" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="steer_effort" value="10.0" />
    <xacro:property name="steer_velocity"
        value="0.5" />
    <xacro:property name="steer_limit_deg" value="35.0" />
    <xacro:macro name="front_wheel_lr"
        params="
        name
        parent
        reflect
        wheel_radius
        wheel_thickness
        wheel_mass
        steer_radius
        steer_thickness
        steer_mass
        base_length
        base_width
        axle_length_offset
        axle_width_offset
        steer_height">

        <link name="${name}_steer_link">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value="${steer_mass}" />
                <inertia
                    ixx="${steer_mass * (3.0 * steer_radius * steer_radius + steer_thickness * steer_thickness) / 12.0}"
                    ixy="0.0" ixz="0.0"
                    iyy="${steer_mass * (3.0 * steer_radius * steer_radius + steer_thickness * steer_thickness) / 12.0}"
                    iyz="0.0"
                    izz="${steer_mass * (steer_radius * steer_radius) / 2.0}" />
            </inertial>
        </link>
        <joint name="${name}_steer_joint" type="revolute">
            <parent link="${parent}_link" />
            <child link="${name}_steer_link" />
            <origin
                xyz="${base_length/2-axle_length_offset} ${reflect*(base_width/2)} ${-0.345}"
                rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <limit effort="${steer_effort}"
                lower="${steer_limit_deg * deg_to_rad * -1.0}"
                upper="${steer_limit_deg * deg_to_rad}"
                velocity="${steer_velocity}" />
        </joint>
        <link name="${name}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${reflect * -pi/2}" />
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Wheel.dae" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${reflect * -pi/2}" />
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Wheel.dae" />
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.7</mu>
                            <mu2>0.7</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="3.512" />
                <inertia ixx="0.02665" ixy="0" ixz="0" iyy="0.0148" iyz="0" izz="0.01479" />
            </inertial>
        </link>
        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${name}_steer_link" />
            <child link="${name}_wheel_link" />
            <origin xyz="0 ${reflect * (wheel_thickness)} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
        <gazebo reference="${name}_steer_link">
            <mu1 value="2.0" />
            <mu2 value="2.0" />
            <kp value="10000000.0" />
            <kd value="1.0" />
            <fdir1 value="0 1 0" />
        </gazebo>

        <gazebo reference="${name}_wheel_link">
            <mu1 value="2.0" />
            <mu2 value="2.0" />
            <kp value="10000000.0" />
            <kd value="1.0" />
            <fdir1 value="0 1 0" />
        </gazebo>
    </xacro:macro>
    <!-- Rear Wheel Links -->
    <xacro:macro name="rear_wheel_lr"
        params="
        name
        parent
        reflect
        wheel_radius
        wheel_thickness
        wheel_mass
        base_length
        base_width
        axle_length_offset
        axle_width_offset">
        <link name="${name}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${reflect * -pi/2}" />
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Wheel.dae" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${reflect * -pi/2}" />
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Wheel.dae" />
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>0.7</mu>
                            <mu2>0.7</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 ${reflect * -pi/2}" />
                <mass value="3.512" />
                <inertia ixx="0.02665" ixy="0" ixz="0" iyy="0.0148" iyz="0" izz="0.01479" />
            </inertial>
            
        </link>
        <joint name="${name}_wheel_joint" type="continuous">
            <parent link="${parent}_link" />
            <child link="${name}_wheel_link" />
            <origin
                xyz="${-(base_length/2-axle_length_offset)} ${reflect*(base_width/2 + wheel_thickness)} ${-0.345}"
                rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
        <gazebo reference="${name}_wheel_link">
            <mu1 value="2.0" />
            <mu2 value="2.0" />
            <kp value="10000000.0" />
            <kd value="1.0" />
            <fdir1 value="0 1 0" />
        </gazebo>
    </xacro:macro>
    <xacro:macro name="door"
        params="
        name
        parent">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Lid.dae" />
                </geometry>
                <origin rpy="0 0 ${-pi/2}" xyz="0.400 -0.002550 0.01750" />
            </visual>
            <collision>
                <origin rpy="0 0 ${-pi/2}" xyz="0.400 -0.002550 0.01750" />
                <geometry>
                    <mesh
                        filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Lid.dae" />
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <mass value="8" />
                <inertia ixx="0.4381" ixy="0" ixz="0" iyy="0.1637" iyz="0.005" izz="0.6" />
            </inertial>
        </link>
        <joint name="${name}_joint" type="revolute">
            <limit lower="0" upper="1.5708" effort="100" velocity="0.5" />
            <origin rpy="0 0 0" xyz="-0.415 0 0.35250" />
            <parent link="${parent}_link" />
            <child link="${name}_link" />
            <axis xyz="0 1 0" rpy="0 0 0" />
        </joint>
    </xacro:macro>
</robot>