<?xml version="1.0"?>

<robot name="deliverybot" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include
        filename="$(find deliverybot_description)/models/deliverybot/xacro/deliverybot_joints.xacro" />
    <xacro:include
        filename="$(find deliverybot_description)/models/deliverybot/xacro/deliverybot_control.xacro" />
    <xacro:property name="robot_namespace" value="/deliverybot" />

    <!-- Gazebo Plugins -->
    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <robotNamespace>${robot_namespace}</robotNamespace>
            <parameters>$(find deliverybot_description)/models/deliverybot/config/controllers.yaml</parameters>
        </plugin>
    </gazebo>

    <!-- Math Constants -->
    <xacro:property name="deg_to_rad" value="0.01745329251994329577" />
    <xacro:property name="steer_limhigh_deg" value="30" />
    <xacro:property name="steer_limlow_deg" value="-30" />
    <!-- Robot Base Dimensions -->
    <xacro:property name="base_length" value="0.85" />
    <xacro:property name="base_width" value="0.35" />
    <!-- <xacro:property name="base_length" value="0.75" /> -->
    <xacro:property name="base_mass" value="72.3" />

    <!-- Wheel Link Dimensions -->
    <xacro:property name="wheel_radius" value="0.125" />
    <xacro:property name="wheel_thickness" value="0.1" />
    <xacro:property name="wheel_mass" value="3.5" />

    <!-- Steering Link Dimensions -->
    <xacro:property name="steer_radius" value="0.1" />
    <xacro:property name="steer_thickness" value="0.02" />
    <xacro:property name="steer_mass" value="1" />

    <!-- Velocity and Movement -->
    <xacro:property name="velocity_limlow" value="-5.0" />
    <xacro:property name="velocity_limhigh" value="8.0" />

    <!-- Axle Positions -->
    <xacro:property name="axle_length_offset" value="0.125" />
    <xacro:property name="axle_width_offset" value="0.1" />
    <xacro:property name="steer_offset" value="-0.15" />
    <!-- Dummy Link -->
    <link name="base_footprint">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
            <geometry>
                <mesh
                    filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Body.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
            <geometry>
                <mesh
                    filename="package://deliverybot_description/models/deliverybot/meshes/EVA_Body.dae" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
            <mass value="64.3" />
            <inertia ixx="8.303" ixy="0" ixz="0" iyy="5.468" iyz="0.075" izz="6.02" />
        </inertial>
    </link>
    <!-- Dummy Joint -->
    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0.470" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>

    <link name="center_steer_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <mass value="${steer_mass}" />
            <inertia
                ixx="${steer_mass * (3.0 * steer_radius * steer_radius + steer_thickness * steer_thickness) / 12.0}"
                ixy="0.0" ixz="0.0"
                iyy="${steer_mass * (3.0 * steer_radius * steer_radius + steer_thickness * steer_thickness) / 12.0}"
                iyz="0.0"
                izz="${steer_mass * (steer_radius * steer_radius) / 2.0}" />
        </inertial>
    </link>
    <joint name="center_steer_joint" type="revolute">
        <parent link="base_link" />
        <child link="center_steer_link" />
        <origin xyz="${base_length/2 - axle_length_offset} 0 -0.345" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="${steer_effort}" lower="${steer_limit_deg * deg_to_rad * -1.0}"
            upper="${steer_limit_deg * deg_to_rad}" velocity="${steer_velocity}" />
    </joint>


    <!-- Steerable Front Wheels -->
    <xacro:front_wheel_lr
        name="front_right"
        parent="base"
        reflect="-1"
        wheel_radius="${wheel_radius}"
        wheel_thickness="${wheel_thickness}"
        wheel_mass="${wheel_mass}"
        steer_radius="${steer_radius}"
        steer_thickness="${steer_thickness}"
        steer_mass="${steer_mass}"
        base_length="${base_length}"
        base_width="${base_width}"
        axle_length_offset="${axle_length_offset}"
        axle_width_offset="${axle_width_offset}"
        steer_height="${wheel_radius+steer_offset}">
    </xacro:front_wheel_lr>
    <xacro:front_wheel_lr
        name="front_left"
        parent="base"
        reflect="1"
        wheel_radius="${wheel_radius}"
        wheel_thickness="${wheel_thickness}"
        wheel_mass="${wheel_mass}"
        steer_radius="${steer_radius}"
        steer_thickness="${steer_thickness}"
        steer_mass="${steer_mass}"
        base_length="${base_length}"
        base_width="${base_width}"
        axle_length_offset="${axle_length_offset}"
        axle_width_offset="${axle_width_offset}"
        steer_height="${wheel_radius+steer_offset}">
    </xacro:front_wheel_lr>

    <xacro:rear_wheel_lr
        name="rear_right"
        parent="base"
        reflect="-1"
        wheel_radius="${wheel_radius}"
        wheel_thickness="${wheel_thickness}"
        wheel_mass="${wheel_mass}"
        base_length="${base_length}"
        base_width="${base_width}"
        axle_length_offset="${axle_length_offset}"
        axle_width_offset="${axle_width_offset}">
    </xacro:rear_wheel_lr>
    <xacro:rear_wheel_lr
        name="rear_left"
        parent="base"
        reflect="1"
        wheel_radius="${wheel_radius}"
        wheel_thickness="${wheel_thickness}"
        wheel_mass="${wheel_mass}"
        base_length="${base_length}"
        base_width="${base_width}"
        axle_length_offset="${axle_length_offset}"
        axle_width_offset="${axle_width_offset}">
    </xacro:rear_wheel_lr> 
    <xacro:door
        name="door"
        parent="base">
    </xacro:door>

    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <xacro:steering_control
            name="center"
            steer_limlow="${steer_limlow_deg * deg_to_rad}"
            steer_limhigh="${steer_limhigh_deg * deg_to_rad}" />
        <xacro:steering_control
            name="front_right"
            steer_limlow="${steer_limlow_deg * deg_to_rad}"
            steer_limhigh="${steer_limhigh_deg * deg_to_rad}" />
        <xacro:velocity_control
            name="front_right"
            velocity_limlow="${velocity_limlow}"
            velocity_limhigh="${velocity_limhigh}" />
        <xacro:steering_control
            name="front_left"
            steer_limlow="${steer_limlow_deg * deg_to_rad}"
            steer_limhigh="${steer_limhigh_deg * deg_to_rad}" />
        <xacro:velocity_control
            name="front_left"
            velocity_limlow="${velocity_limlow}"
            velocity_limhigh="${velocity_limhigh}" />
        <xacro:velocity_control
            name="rear_right"
            velocity_limlow="${velocity_limlow}"
            velocity_limhigh="${velocity_limhigh}" />
        <xacro:velocity_control
            name="rear_left"
            velocity_limlow="${velocity_limlow}"
            velocity_limhigh="${velocity_limhigh}" />
        <xacro:door_control
            name="door"
            door_limlow="${0 * deg_to_rad}"
            door_limhigh="${90 * deg_to_rad}" />
    </ros2_control>
</robot>